### PR TITLE
Fix #889

### LINKED ISSUE #889: mail.yahoo.com
### Screenshot of the web page (including address bar and extension icons) (required): 
image

### Screenshot of the console (press `F12` to bring up the console) (required): 

image

### Environment (Required): 
Windows 10 v. 1709 

- Browser and Version: 
Chrome Version 65.0.3325.181 (Official Build) (64-bit)
- Adblocker and Version: 
uBlock Origin v1.15.2

#### Your filter lists (Required): 
default + Nano Defender

### PR DESCRIPTION
**Pull request by geoffdutton**
This fixes #889. I have a yahoo account, and this blocks the message.

### CODE REVIEW

**Comment by jspenguin2017** [comment]
@jctam can you test? 

cc @okiehsch

**Comment by jspenguin2017** [comment]
Also @geoffdutton You should change `/list/3-rules.txt` instead of the compiled binary.

**Comment by okiehsch** [comment]
I can't test, I do not have a yahoo account. 
If the OP of the issue confirms that the fix works for him I will add it.

**Comment by lain566** [comment]
I can provide a yahoo account for testing. I've just sent you a confidential issue

**Comment by jspenguin2017** [comment]
@lain566 Thanks. Confirmed working. Structure for future reference: 
image

**Comment by jspenguin2017** [comment]
Commit: https://github.com/NanoAdblocker/NanoFilters/commit/f6bb00376fdbfe43fe57621f91e5bcd8a03fccd5

**Pull request merged**
